spring.datasource.url=jdbc:mysql://localhost:3306/kinoxp
spring.datasource.username=${usernam}
spring.datasource.password=${passwor}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=never