spring.datasource.url=jdbc:mysql://localhost:3306/kinoxp
spring.datasource.username=envusernamegoeshere
spring.datasource.password=envpasswordgoeshere
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver